"""GANDIV Markdown Reporter - GitHub-compatible, git-friendly, email-shareable."""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from gandiv.models import ScanResult

RISK_EMOJI = {
    "critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪",
}
CONF_EMOJI = {"high": "✅", "medium": "🟨", "low": "❓"}


def generate(scan_result: ScanResult, output_path: Path) -> Path:
    scan_result.compute_stats()
    lines = []
    t = scan_result.target
    lines.append(f"# GANDIV OSINT Report — `{t.normalized}`")
    lines.append("")
    lines.append(f"- **Scan ID:** `{scan_result.scan_id}`")
    lines.append(f"- **Target type:** {t.type.value}")
    lines.append(f"- **Started:** {scan_result.started_at}")
    lines.append(f"- **Finished:** {scan_result.finished_at or 'in progress'}")
    lines.append(f"- **Total findings:** {scan_result.stats.get('total_findings', 0)}")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Risk | Count |")
    lines.append("|---|---|")
    for risk, count in scan_result.stats.get("by_risk", {}).items():
        lines.append(f"| {RISK_EMOJI.get(risk, '')} {risk.title()} | {count} |")
    lines.append("")

    lines.append("## Module Results")
    lines.append("")
    lines.append("| Module | Status | Findings | Duration (s) | Sources Used |")
    lines.append("|---|---|---|---|---|")
    for m in scan_result.module_results:
        status = "✅ success" if m.success else "❌ failed"
        lines.append(
            f"| {m.module_name} | {status} | {len(m.findings)} | "
            f"{m.duration_seconds:.2f} | {', '.join(m.sources_used) or '—'} |"
        )
    lines.append("")

    by_type = defaultdict(list)
    for f in scan_result.findings:
        by_type[f.type].append(f)

    lines.append("## Findings by Category")
    lines.append("")
    for ftype in sorted(by_type.keys()):
        group = sorted(by_type[ftype], key=lambda f: (-_risk_rank(f.risk.value), -f.score))
        lines.append(f"### {ftype.replace('_', ' ').title()} ({len(group)})")
        lines.append("")
        lines.append("| Value | Confidence | Risk | Source(s) | Score |")
        lines.append("|---|---|---|---|---|")
        for f in group[:200]:  # keep file readable
            value = f.value.replace("|", "\\|")
            src = ", ".join(f.corroborated_by) if f.corroborated_by else f.source
            lines.append(
                f"| `{value}` | {CONF_EMOJI.get(f.confidence.value, '')} {f.confidence.value} "
                f"| {RISK_EMOJI.get(f.risk.value, '')} {f.risk.value} | {src} | {f.score:.2f} |"
            )
        if len(group) > 200:
            lines.append(f"\n_...and {len(group) - 200} more (see JSON report for full data)._")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by GANDIV — authorized reconnaissance only._")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def _risk_rank(risk: str) -> int:
    order = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}
    return order.get(risk, 0)
